import * as fs from 'node:fs';
import * as path from 'node:path';
import { Files } from './files.ts';
import type { Profile } from './install.ts';

export class Agents {
  constructor(private files: Files, private profile: Profile) {}

  private generated(profile: Profile) {
    return path.join(this.files.repo, '.generated/agents', profile, 'AGENTS.md');
  }

  async apply(uninstall: boolean) {
    const global = path.join(this.files.repo, 'shared/agents/global/AGENTS.md');
    const destinations = [
      path.join(process.env.CODEX_HOME || path.join(this.files.home, '.codex'), 'AGENTS.md'),
      path.join(process.env.CLAUDE_CONFIG_DIR || path.join(this.files.home, '.claude'), 'CLAUDE.md'),
    ];
    if (uninstall) {
      for (const destination of destinations) {
        for (const source of [global, this.generated('macos'), this.generated('omarchy')]) {
          this.files.unlink(source, destination);
        }
      }
      return;
    }
    const context = path.join(this.files.repo, this.profile === 'macos' ? 'macos' : 'linux', 'agents/CONTEXT.md');
    // Read all source instructions before changing a generated file or runtime link.
    const sections = [global, context].map(source => {
      const content = fs.readFileSync(source, 'utf8').trim();
      if (!content) throw new Error(`${source}: instructions are empty`);
      return content;
    });
    const content = [
      '<!-- Generated by ./cli --only agents. Edit shared/agents/global/AGENTS.md and the matching OS CONTEXT.md, then rerun the CLI. -->',
      ...sections,
      '## Machine inventory',
      `For provisioning or cross-machine work, read \`${path.join(this.files.repo, 'COMPUTERS.md')}\` and the local connection records in \`${path.join(this.files.repo, 'COMPUTERS.local.md')}\`. Match the actual hostname to its record; do not infer a machine role from its OS.`,
    ].join('\n\n') + '\n';
    const generated = this.generated(this.profile);
    const identical = fs.existsSync(generated) && fs.readFileSync(generated, 'utf8') === content;
    this.files.log(identical ? 'skip' : 'compose', `${this.files.pretty(generated)} from shared instructions + ${this.files.pretty(context)}`);
    if (!this.files.dryRun && !identical) {
      fs.mkdirSync(path.dirname(generated), { recursive: true, mode: 0o700 });
      const temporary = `${generated}.${process.pid}.tmp`;
      fs.writeFileSync(temporary, content, { mode: 0o600 });
      fs.renameSync(temporary, generated);
    }
    for (const destination of destinations) await this.files.link(generated, destination, false, this.files.dryRun ? content : undefined);
  }
}
