import * as fs from 'node:fs';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { Files, run } from './files.ts';
import type { Profile } from './install.ts';

const timer = 'mise-prune.timer';
// Homebrew's prefixes are absent from launchd's default PATH.
const launchdPath = '/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin';

function escape(text: string) {
  return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function plist(label: string, script: string, schedule: string) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by ./cli --only mise. Edit scripts/lib/mise.ts, then rerun the CLI. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>${escape(script)}</string>
  </array>
${schedule}
</dict>
</plist>
`;
}

export class Mise {
  constructor(private files: Files, private profile: Profile) {}

  private agents() {
    const helper = path.join(this.files.repo, 'macos/bin/xcode-node-env');
    const log = path.join(this.files.home, 'Library/Logs/dev.dstech.mise-prune.log');
    return [
      // GUI apps such as Xcode and Android Studio start with launchd's PATH, not
      // the shell's. The shims select each project's tool versions from its cwd.
      ['dev.dstech.guipath', plist('dev.dstech.guipath',
        `/bin/launchctl setenv PATH "$HOME/.local/share/mise/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"`,
        '  <key>RunAtLoad</key>\n  <true/>')],
      // Repoint Xcode at the Node shim before pruning removes recorded install paths.
      ['dev.dstech.mise-prune', plist('dev.dstech.mise-prune',
        `export PATH="${launchdPath}"; "${helper}"; exec mise prune --yes`,
        `  <key>StartCalendarInterval</key>\n  <dict>\n    <key>Hour</key>\n    <integer>12</integer>\n    <key>Minute</key>\n    <integer>30</integer>\n  </dict>\n  <key>StandardOutPath</key>\n  <string>${escape(log)}</string>\n  <key>StandardErrorPath</key>\n  <string>${escape(log)}</string>`)],
    ] as const;
  }

  private generated(label: string) {
    return path.join(this.files.repo, '.generated/launchd', `${label}.plist`);
  }

  private launchctl(args: string[], required = true) {
    if (required) run('launchctl', args);
    else spawnSync('launchctl', args, { stdio: 'ignore' });
  }

  private async macos(uninstall: boolean) {
    const uid = process.getuid?.();
    if (uid === undefined) throw new Error('launchd agents need a POSIX user id');
    const domain = `gui/${uid}`;
    for (const [label, content] of this.agents()) {
      const generated = this.generated(label);
      const destination = path.join(this.files.home, 'Library/LaunchAgents', `${label}.plist`);
      if (uninstall) {
        if (this.files.target(destination) !== generated) continue;
        this.files.log('unload', `launchd agent ${label}`);
        if (!this.files.dryRun) this.launchctl(['bootout', `${domain}/${label}`], false);
        this.files.unlink(generated, destination);
        continue;
      }
      const identical = fs.existsSync(generated) && fs.readFileSync(generated, 'utf8') === content;
      this.files.log(identical ? 'skip' : 'compose', `${this.files.pretty(generated)} launchd agent`);
      if (!this.files.dryRun && !identical) {
        fs.mkdirSync(path.dirname(generated), { recursive: true });
        fs.writeFileSync(generated, content);
      }
      await this.files.link(generated, destination, false, this.files.dryRun ? content : undefined);
      if (this.files.target(destination) !== generated && !this.files.dryRun) continue;
      this.files.log('load', `launchd agent ${label}`);
      if (!this.files.dryRun) {
        // Bootstrap fails while the agent is loaded, so reload it to pick up changes.
        this.launchctl(['bootout', `${domain}/${label}`], false);
        this.launchctl(['bootstrap', domain, destination]);
      }
    }
  }

  private async omarchy(uninstall: boolean) {
    const units = path.join(this.files.home, '.config/systemd/user');
    if (uninstall) {
      this.files.log('disable', `systemd user timer ${timer}`);
      if (!this.files.dryRun) spawnSync('systemctl', ['--user', 'disable', '--now', timer], { stdio: ['inherit', 'inherit', 'ignore'] });
    }
    for (const unit of ['mise-prune.service', timer]) {
      const source = path.join(this.files.repo, 'omarchy/mise', unit), destination = path.join(units, unit);
      if (uninstall) this.files.unlink(source, destination);
      else await this.files.link(source, destination);
    }
    if (!uninstall) this.files.log('enable', `systemd user timer ${timer}`);
    if (!this.files.dryRun) {
      run('systemctl', ['--user', 'daemon-reload']);
      if (!uninstall) run('systemctl', ['--user', 'enable', '--now', timer]);
    }
  }

  async apply(uninstall: boolean) {
    const fragment = path.join(this.files.repo, 'shared/mise/conf.d/donnes.toml');
    const destination = path.join(this.files.home, '.config/mise/conf.d/donnes.toml');
    if (uninstall) this.files.unlink(fragment, destination);
    else await this.files.link(fragment, destination);
    await (this.profile === 'macos' ? this.macos(uninstall) : this.omarchy(uninstall));
  }
}
